SolucionEF/EFMVC/Models/ProductoView.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFMVC.Models
{
    public class ProductoView
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "Por favor ingrese un nombre")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Por favor ingrese entre 3 y 40 caeacteres.")]
        public String Nombre { get; set; }


        [StringLength(20, ErrorMessage = "Por favor ingrese no más de 20 caeacteres.")]
        public String CantidadPorUnidad { get; set; }


        [Display(Name = "Precio unitario")]
        [DataType(DataType.Currency)]
        public Decimal PrecioUnitario { get; set; }

    }
}

SolucionEF/EFMVC/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace EFMVC.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            ViewBag.errorMessage = TempData["errorMessage"];
            return View();
        }
    }
}

SolucionEF/EFMVC/Controllers/PaisController.cs
using EFEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using System.Web.Mvc;
using EFCapaLogica;
using PagedList;

namespace EFMVC.Controllers
{
    public class PaisController : Controller
    {
        // GET: Pais
        public ActionResult Index(int? page)
        {
            try
            {
                LogicaPais logica = new LogicaPais();

                List<Countries> paises = logica.ObtenerPaisesPorIdioma("es");

                int pageSize = 10;
                int pageNumber = page ?? 1;

                return View(paises.ToPagedList(pageNumber, pageSize));
            }
            catch (ExcepcionPersonalizadaMVC ep)
            {
                TempData["errorMessage"] = "Error: " + ep.Message;
                return RedirectToAction("Index", "Error");
            }
        }

    }

}

SolucionEF/EFMVC/Controllers/ProductoController.cs
using EFCapaLogica;
using EFEntities;
using EFMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using PagedList;

namespace EFMVC.Controllers
{
    public class ProductoController : Controller
    {
        LogicaProductos logicaProductos = new LogicaProductos();

        // GET: Producto
        public ActionResult Index(int? page)
        {
            try
            {
                List<Products> listaProductos = logicaProductos.ObtenerTodos();
                List<ProductoView> listaVistaProducto = listaProductos.Select(p => new ProductoView
                {
                    Id = p.ProductID,
                    Nombre = p.ProductName,
                    CantidadPorUnidad = p.QuantityPerUnit,
                    PrecioUnitario = (decimal)p.UnitPrice
                }).ToList();

                int pageSize = 10;
                int pageNumber = page ?? 1;
  
                return View(listaVistaProducto.ToPagedList(pageNumber,pageSize));
            }
            catch (ExcepcionPersonalizadaMVC ep)
            {
                TempData["errorMessage"] = "Error: " + ep.Message;
                return RedirectToAction("Index", "Error");
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = "Error: " + e.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        // GET: Producto/Ver/5
        public ActionResult Ver(int id)
        {
            try
            {
                Products producto = logicaProductos.BuscarProductoPorId(id);
                ProductoView productView = new ProductoView
                {
                    Id = producto.ProductID,
                    Nombre = producto.ProductName,
                    CantidadPorUnidad = producto.QuantityPerUnit,
                    PrecioUnitario = (decimal)producto.UnitPrice
                };

                return View(productView);
            }
            catch (ExcepcionPersonalizadaMVC ep)
            {
                TempData["errorMessage"] = "Error: " + ep.Message;
                return RedirectToAction("Index", "Error" );
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = "Error: " + e.Message;
                return RedirectToAction("Index", "Error");
            }
        }

        //GET: Producto/AltaYEdicion
        public ActionResult AltaYEdicion(int id)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                try
                {
                    Products producto = logicaProductos.BuscarProductoPorId(id);
                    ProductoView productoView = new ProductoView
                    {
                        Id = producto.ProductID,
                        Nombre = producto.ProductName,
                        CantidadPorUnidad = producto.QuantityPerUnit,
                        PrecioUnitario = (decimal)producto.UnitPrice,
                    };
                    return View(productoView);
                }
                catch (ExcepcionPersonalizadaMVC ep)
                {
                    TempData["errorMessage"] = "Error: " + ep.Message;
                    return RedirectToAction("Index", "Error");
                }
                catch (Exception e)
                {
                    TempData["errorMessage"] = "Error: " + e.Message;
                    return RedirectToAction("Index", "Error");
                }
            }
        }

        //POST: Producto/AltaYEdicion
        [HttpPost]
        public ActionResult AltaYEdicion(ProductoView productoView)
        {
            if (ModelState.IsValid)
            {
                Products producto = new Products
                {
                    ProductID = productoView.Id,
                    ProductName = productoView.Nombre,
                    QuantityPerUnit = productoView.CantidadPorUnidad,
                    UnitPrice = productoView.PrecioUnitario
                };

                if (productoView.Id == 0) //Alta
                {
                    //En este método no se utiliza try-catch ya que la capa lógica maneja
                    //la excepción y deuelve false en caso de no haber podido guardar el productoView

                    try
                    {
                        logicaProductos.Agregar(producto);
                        return RedirectToAction("Index");
                    }
                    catch (Exception e)
                    {
                        TempData["errorMessage"] = "No se pudo guardar el producto. Detalle: " + e.Message;
                        return RedirectToAction("Index", "Error");
                    }
                }
                else    //Editar
                {
                    

                    try
                    {
                        logicaProductos.Actualizar(producto);
                        return RedirectToAction("Index");
                    }
                    catch (Exception e)
                    {
                        TempData["errorMessage"] = "No se pudo actualizar el producto. Detalle: " + e.Message;
                        return RedirectToAction("Index", "Error");
                    }

                }
            }
            else
            {
                return View();
            }
            
        }
        // GET: Producto/Delete/5
        public ActionResult Borrar(int id)
        {

            try
            {
                logicaProductos.Borrar(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = "No se pudo eliminar el producto. Detalle: " + e.Message;
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

SolucionEF/EFMVC/Views/Pais/Index.cshtml
@model PagedList.IPagedList<EFEntities.Countries>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Nuestros Clientes";
}

<div class="titulo">
    <h1 class="text-uppercase text-center my-md-5">Nuestros clientes</h1>
</div>
<hr />
<h3 class="text-center my-md-5">Llegamos a todos los paises de habla hispana</h3>

<div class="contenido">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">SUBREGION</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">CAPITAL</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pais in Model)
            {
                <tr>
                    <td>@pais.Subregion</td>
                    <td>@pais.Name </td>
                    <td>@pais.Capital</td>
                </tr>
            }

        </tbody>
    </table>

    <br />

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

</div>

SolucionEF/EFMVC/Views/Producto/AltaYEdicion.cshtml
@model EFMVC.Models.ProductoView
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <div class="titulo">
        <h1 class="text-uppercase text-center my-md-5">Nuevo producto</h1>
    </div>
}
else
{
    <div class="titulo">
        <h1 class="text-uppercase text-center my-md-5">Editar producto</h1>
    </div>
}
<hr />
<div class="contenido">
    @using (Html.BeginForm("AltaYEdicion", "Producto", FormMethod.Post))
    {

        <div class="form-group">
            <label>Nombre</label>

            @(Html.TextBoxFor(p => p.Nombre, new { @class= "form-control", placeholder="Nombre del producto"}))
            @Html.ValidationMessageFor(p => p.Nombre)

        </div>

        <div class="form-group">
            <label>Presentación</label>
            @(Html.TextBoxFor(p =>p.CantidadPorUnidad, new { @class = "form-control", placeholder = "Presentación del producto" }))
            @Html.ValidationMessageFor(p => p.CantidadPorUnidad)

        </div>

        <div class="form-group">
            <label>Precio unitario</label>

            @(Html.TextBoxFor(p =>p.PrecioUnitario, new { @class = "form-control", placeholder = "Precio del producto" }))
            @Html.ValidationMessageFor(p => p.PrecioUnitario)

        </div>

        <br /><br />
        <input type="submit" class="btn btn-primary" value="Guardar Cambios" />

    }

</div>

SolucionEF/EFMVC/Views/Producto/Index.cshtml
@model PagedList.IPagedList<EFMVC.Models.ProductoView>

@using PagedList.Mvc;

@{
    ViewBag.Title = "Lista de productos";
}

<div class="titulo">
    <h1 class="text-uppercase text-center my-md-5">Lista de los productos</h1>
</div>
<hr />
<div class="contenido">
    <div>
        @Html.ActionLink(" ", "AltaYEdicion", new { id = 0 }, new { @class = "btn btn-primary glyphicon glyphicon-plus-sign" })
    </div>


    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOMBRE</th>
                <th scope="col">CANTIDAD POR UNIDAD</th>
                <th scope="col">PRECIO POR UNIDAD</th>
                <th scope="col" colspan="3"><center>ACCIONES</center></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var producto in Model)
            {
                var tm = "#myModal" + producto.Id;
                var mid = "myModal" + producto.Id;
                <tr>
                    <th scope="row">@producto.Id </th>
                    <td>@producto.Nombre</td>
                    <td>@producto.CantidadPorUnidad</td>
                    <td>@producto.PrecioUnitario</td>
                    <td>@Html.ActionLink(" ", "Ver", new { id = producto.Id }, new { @class = "btn btn-primary glyphicon glyphicon-eye-open" })</td>
                    <td>@Html.ActionLink(" ", "AltaYEdicion", new { id = producto.Id }, new { @class = "btn btn-primary glyphicon glyphicon-pencil" })</td>
                    <td>
                        <button type="button" class="btn btn-primary glyphicon glyphicon-trash" data-toggle="modal" data-target="@tm">
                        </button>
                        <div class="modal fade" id="@mid" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title" id="myModalLabel">¡Advertencia!</h4>
                                    </div>
                                    <div class="modal-body">
                                        ¿Usted en verdad está seguro de eliminar este producto?
                                    </div>
                                    <div class="modal-footer">
                                        @Html.ActionLink("Eliminar", "Borrar", new { id = producto.Id }, new { @class = "btn btn-primary" })

                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </td>

                </tr>
            }

        </tbody>
    </table>

    <br />

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new {page }))

</div>

SolucionEF/EFMVC/Views/Producto/Ver.cshtml
@model EFMVC.Models.ProductoView
@{
    ViewBag.Title = "Ver";
}

<div class="titulo">
    <h1 class="text-uppercase text-center my-md-5">Detalle del producto</h1>
</div>



<hr />
<div class="contenido">
    @using (Html.BeginForm("Ver", "Producto"))
    {

        <div class="form-group">
            <label>Nombre</label>

            @(Html.TextBoxFor(p => p.Nombre, new { @class= "form-control", placeholder= "Nombre del producto", @readonly = "readonly"  }))

        </div>

        <div class="form-group">
            <label>Presentación</label>
            @(Html.TextBoxFor(p =>p.CantidadPorUnidad, new { @class = "form-control", placeholder = "Presentación del producto", @readonly = "readonly" }))

        </div>

        <div class="form-group">
            <label>Precio unitario</label>

            @(Html.TextBoxFor(p =>p.PrecioUnitario, new { @class = "form-control", placeholder = "Precio del producto" , @readonly = "readonly"  }))

        </div>

        <br /><br />
        @Html.ActionLink("Volver", "Index", "Producto",new { @class = "btn btn-primary" }) 


    }

</div>

SolucionEF/EFMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Practica ABMC MVC", "Index", "Producto", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Producto", "Index", "Producto")</li>
                    <li>@Html.ActionLink("Nuestros Clientes", "Index", "Pais")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <!-- Footer -->
        <footer class="page-footer font-small blue">

            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                © 2021 Copyright:
                <a href="https://www.neoris.com/" target="_blank"> neoris.com</a>
            </div>
            <!-- Copyright -->

        </footer>
        <!-- Footer -->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>